### ISSUE TITLE
Move IoPlugin impl to .cpp file!

### ISSUE THREAD

**Issue by alaurenzi** [ADVRHumanoids/XCM#10]
I've just noticed that I left the implementation of IoPlugin.h inside the header file (and it is not even inlined!), so I need to move it to a cpp file in order to avoid possibile multiple definition issues

**Comment by alaurenzi** [comment]
Solved in **issue10**, but I am not able to test it right now (I would need to update some repos in order to have compatibility with the latest updates)... maybe @liesrock  or @pepperig  can check it and possibly merge to master?

**Comment by liesrock** [comment]
Tested with IkRosIo and merged in 9ff93d5e9bd50bced09aae70231a84c644d25bd4
