### ISSUE TITLE
Effort command from ROS is not sent to the robot

### ISSUE THREAD

**Issue by alaurenzi** [ADVRHumanoids/XCM#2]
Issue ADVRHumanoids/GazeboXBotPlugin#1 actually depends on XCM! @domingoesteban @liesrock 
I am creating a new branch XCM_issue2 to solve the problem

**Comment by alaurenzi** [comment]
Trying to solve the issue in f0e0c6e62d, to me it works in a simple test, please provide feedback! @liesrock  @domingoesteban

**Comment by liesrock** [comment]
With @domingoesteban we are trying to check the commit: we need master updated version of RobotInterfaceROS

**Comment by domingoesteban** [comment]
Ciao @alaurenzi , wrt your [comment](https://github.com/ADVRHumanoids/GazeboXBotPlugin/issues/1#issuecomment-307338820) does this mean that **every** command should be like:
name: ['LShSag']
position: []
velocity: []
effort: [-50]
stiffness: [0]
damping: [0]
aux_name: ''
aux: []`
??

**Comment by alaurenzi** [comment]
Well, when you have set the impendance to zero once, you can send messages with empty impendance field!

**Comment by domingoesteban** [comment]
@alaurenzi thanks, today I was testing and it seems to work!
Just 1 more comments:
I was also checking the impedance gains in the ROS JointStateAdvr message and they are the same initial gains. Is this OK? or they should be the last impendance gains that were set in the CommandAdvr??

**Comment by alaurenzi** [comment]
Well, no it is a problem... Today I try to check. Thanks for the feedback!

**Comment by alaurenzi** [comment]
I am not able to reproduce the issue in a simple test, meaning that I if I change the impedance via CommandAdvr messages I am also able to read the modified value from the JointState message

**Comment by domingoesteban** [comment]
Sorry, I've just checked I was wrong. My bad.

**Comment by alaurenzi** [comment]
Perfect! I'll change the status to closed as soon as merged to master

**Comment by liesrock** [comment]
This is solved.
