### ISSUE TITLE
Dynamic load/unload plugins

### ISSUE THREAD

**Issue by pepperig** [ADVRHumanoids/XCM#23]
One simple solution is the following:
Create the instance of the plugin handler in the Main that create the RT thread and pass the reference.
We create another thread that handles the load and unload of the plugins.
We need tho have a service like namepulugin_restart that simply stop the plugin and in the mean time the other thread deals with unloading or loading of the plugin.
Could it works?
@liesrock @alaurenzi

**Comment by alaurenzi** [comment]
This is very important. Right now we need to restart the robot/gazebo every time that we make some modification to a plugin. This slows down the development a lot, and defeats half of the purpose of using dynamic loading.

**Comment by alaurenzi** [comment]
@pepperig  Share your results!!

**Comment by pepperig** [comment]
@alaurenzi I need to test it on Xenomai. Plus I am trying to solve all the seg fault in closure phase and replacing shalipbb.

**Comment by pepperig** [comment]
done. it works in xenomai
