### ISSUE TITLE
XBotCommunicationPlugin by terminal

### ISSUE THREAD

**Issue by pepperig** [ADVRHumanoids/XCM#25]
Whenever we try to publish the topic using rostopic pub we get no result. We tried to move the head and it works just the first time. I remember it was working. The GUI is working though. Can you check it out?
@alaurenzi

**Comment by alaurenzi** [comment]
So the problem was due to the impedance gains being set to 0 by mistake! Let us remember to check
that we do not send zero impedance when publishing references via command line!
