### ISSUE TITLE
Moving Hand from NRTPlugin

### ISSUE THREAD

**Issue by pepperig** [ADVRHumanoids/XCM#26]
Hi,

As you know we have a centralized manipulation RT Plugin that we use to let NRT plugin execute manipulation tasks. We should do the same with the grasping because right now we cannot command the hand while there are other RT plugins running. 
@liesrock @alaurenzi

**Comment by liesrock** [comment]
@alaurenzi do you have any free time to implement this today? Otherwise I will take care of it during the Florence's days.

**Comment by pepperig** [comment]
done
