### ISSUE TITLE
On the config files revolution.

### ISSUE THREAD

**Issue by liesrock** [ADVRHumanoids/XCM#32]
Here you can find a recap of all the considerations/choices I took to carry out the so called "config files revolution".

**Requirements** 

1. Maintainability: we should be able to separate the _user config files_ from the _low level/core details_ in order to have a way to update separately the two different layers.

2. Easy to use: the user should specify in the _user config files_ only a minimum subset of option related with his/her high level choices.

3. Portability: it should be easy to port the _default config files_ on different systems, at least with the superbuild support.

4. Flexibility: it should be trivial to change the config file in use both in simulation and on the real robot and both for the _user config files_ and the _low level/core details_ .

**Comment by liesrock** [comment]
**Implementation**

- _low level/core details_ stored in the ADVR_shared (branch arvigo): both the gains in simulation and on the real robot are stored there. 

- _user config files_ will be placed in the user repos (you can find and example in ADVR_shared branch arvigo under the folder user_example).

- a script in the superbuild called set_xbot_config will let the user choose which  _user config files_ to use as _default config file_  in his/her system (advr-superbuild branch arvigo).

- once called the set_xbot_config the user needs to source the .bashrc on the already open terminals.

- a core.yaml file will be provided in the superbuild.

- XCM. XBotInterface, RobotInterfaceROS, GazeboXBotPlugin are all on arvigo if you want to try it.

@pepperig @alaurenzi @EnricoMingo PLEASE: check the new config file policy and let me know your opinion. After this I will proceed with the merge.

**Comment by pepperig** [comment]
Also the XBotCore reads the config file..is this working?
Would be great to have an automatic source after running the script
@liesrock

**Comment by alaurenzi** [comment]
+1 for the automatic sourcing across terminals (easiest solution: xbot_set_configs writes to a file that acts as shared memory between terminals)
Moreover it would be nice to provide the possibility to set the config file through the ros parameter server. Priorities could be like this:
- config from command line
- config from parameters server
- config from XBot::GetConfig (if this is the proper name :D) @liesrock  @pepperig

**Comment by pepperig** [comment]
I would prefer to not depend on ROS for the config file. If we want use ROS this should be the last priority in my opinion

**Comment by alaurenzi** [comment]
Any news on this? Arvigo is waiting for us

**Comment by liesrock** [comment]
bravo! I can't merge until we stop with sprint weeks or missions....I will try to see if it is possible during these days.

**Comment by liesrock** [comment]
Thanks @pepperig, I will do the same for XBotCore: now I am going to merge everything in the devel branch.

**Comment by liesrock** [comment]
Merging first in devel and then in master: once available and tested on master I will close it.

**Comment by liesrock** [comment]
Merged in master: writing down proper documentation.
