### ISSUE TITLE
Error compiling XCM

### ISSUE THREAD

**Issue by alessandrosettimi** [ADVRHumanoids/XCM#34]
Starting from a clear build I had to add the following in the package.xml to make XCM compile:

```
<build_depend>message_generation</build_depend>
```

**Comment by liesrock** [comment]
Hi @alessandrosettimi , which operating system are you using? Can you give us more details about the versions of the package you are using?
I suspect this is due to an update.

**Comment by alessandrosettimi** [comment]
- Ubuntu 16.04
- which package? 

P.S. I had to do the same to trajectory_utils and ADRV_ROS to make the superbuild compile.

**Comment by liesrock** [comment]
Thanks for the info @alessandrosettimi : did you push it?

**Comment by alessandrosettimi** [comment]
@DaniloCaporale pushed in c3cf9c4a9f5e8eca804108873062cbf612fd17e5

**Comment by liesrock** [comment]
Super!
