### ISSUE TITLE
Merge XCM & XBotCore

### ISSUE THREAD

**Issue by alaurenzi** [ADVRHumanoids/XCM#36]
Now that XBotCore does not contain low level code anymore (thanks @pepperig), to me it does not make sense to have two separate repos. What do you think @pepperig @liesrock @EnricoMingo ?

**Comment by pepperig** [comment]
As we discussed I agree but we should have a way to preserve all the history after merged.

**Comment by liesrock** [comment]
Thanks @alaurenzi @pepperig: I agree and I will follow this https://stackoverflow.com/questions/1425892/how-do-you-merge-two-git-repositories

The question is when are we going to do all the changes? I will ask for two days (2,3 November) to perform all our new changes and merges.

**Comment by pepperig** [comment]
I would try first on 2 example repository

**Comment by pepperig** [comment]
To me there is no rush to merge. I would wait to solve first all the other issues. @alaurenzi  @liesrock

**Comment by liesrock** [comment]
Ok I will take care of it, no worries!

**Comment by alaurenzi** [comment]
For sure it is not a priority, but to me the best repo organization is the following:
- XBotCore (current XBotCore + XCM + all HAL implementations [conditional build con flags cmake])
- XBotInterface (current XBotInterface + XBotCoreModel + all RobotInterface/ModelInterface)
- GazeboXbotPlugin

**Comment by pepperig** [comment]
For the HAL implementation I would leave them as separated repositories.  Anyway I think that each module that is able to work independently can be a repo (like so library). XCM and XBotCore depends on each other, so it make sense merge them. I do not know so much about the XBotInterface.

**Comment by liesrock** [comment]
I would put also XBotInteface.

**Comment by EnricoMingo** [comment]
Hi all, one question related to RobotInterface/Modelinterface: does these requires XCM+XBotCore for the compilation (with the last changes)?


Inviato da iPhone

**Comment by pepperig** [comment]
done
