### ISSUE TITLE
Wrong set schedpolicy in NRT Communication Handler

### ISSUE THREAD

**Issue by liesrock** [ADVRHumanoids/XCM#40]
As @alaurenzi noticed, there is probably a bug on the set schedpolicy of the CommunicationHandler.

**Comment by alaurenzi** [comment]
Yes, more specifically Margan's `ThreadHook` class will set the scheduling policy **before** calling th_init(), and so it is important to set it inside the constructor!

**Comment by alaurenzi** [comment]
Solved in devel

**Comment by liesrock** [comment]
Good catch @alaurenzi !
