### ISSUE TITLE
[WALK-MAN] CommunicationHandler config file 

### ISSUE THREAD

**Issue by EnricoMingo** [ADVRHumanoids/XCM#43]
Communication handler config file should be the one which contains the walk-man model WITHOUT the multisense (namely bigman_real.urdf

**Comment by alaurenzi** [comment]
This is clearly a HACK. We can do it for the final demo, but for other robots a better solution must be found. For example, we can put different names to the frames of the head that we use for control (e.g. `multisense_ctrl`)

**Comment by alaurenzi** [comment]
This notwithstanding (+1 for the english), with ADVRHumanoids/XBotCore@9885c5aef05ac9dad2e7cd4310f I introduced the possibility to specify a custom Commhandler config file with a `--ch-config`

**Comment by liesrock** [comment]
http://www.wordreference.com/enit/notwithstanding
