### ISSUE TITLE
Fake IMU & FT measurements from ROS

### ISSUE THREAD

**Issue by alaurenzi** [ADVRHumanoids/XCM#7]
The original issue was opened as ADVRHumanoids/GazeboXBotPlugin#2

**Comment by alaurenzi** [comment]
Solving it in XCM_issue7 branch

**Comment by alaurenzi** [comment]
Solved in e7912fe5caf0fca84af1d2d4c16a6cda5d5dcd72 @liesrock  @vigisushrutha23

**Comment by liesrock** [comment]
Thnaks @alaurenzi
