### ISSUE TITLE
Generating plugin script

### ISSUE THREAD

**Issue by pepperig** [ADVRHumanoids/XCM#8]
I would suggest to have a script that as first step creates the the plugin's folder. Otherwise, if you are not paying attention and run the script in the external folder, you end up in overwriting the others folder's file.
@liesrock  @alaurenzi

**Comment by alaurenzi** [comment]
I personally like the idea! Also have a look to #4 which is somehow related

**Comment by liesrock** [comment]
Perfect: we merge the two issue together and try to have the implementation asap.

**Comment by pepperig** [comment]
Solved
